// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

// 为某个枚举单独设置错误码
func IsNeedLogin(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_NEED_LOGIN.String() && e.Code == 401
}

// 为某个枚举单独设置错误码
func ErrorNeedLogin(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ErrorReason_NEED_LOGIN.String(), fmt.Sprintf(format, args...))
}

func IsDbFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_DB_FAILED.String() && e.Code == 500
}

func ErrorDbFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_DB_FAILED.String(), fmt.Sprintf(format, args...))
}

// 订单已经评价过
func IsOrderReviewed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_ORDER_REVIEWED.String() && e.Code == 400
}

// 订单已经评价过
func ErrorOrderReviewed(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_ORDER_REVIEWED.String(), fmt.Sprintf(format, args...))
}

// 评价已经被（商家）回复过
func IsReviewReplyed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_REVIEW_REPLYED.String() && e.Code == 400
}

// 评价已经被（商家）回复过
func ErrorReviewReplyed(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_REVIEW_REPLYED.String(), fmt.Sprintf(format, args...))
}

// 商家不能回复另一个商家的评论
func IsCannotReplyOhterStoreReview(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CANNOT_REPLY_OHTER_STORE_REVIEW.String() && e.Code == 400
}

// 商家不能回复另一个商家的评论
func ErrorCannotReplyOhterStoreReview(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_CANNOT_REPLY_OHTER_STORE_REVIEW.String(), fmt.Sprintf(format, args...))
}
